"""Framework-independent source capability, separate from audit persistence."""
from typing import Any, Protocol


class CompanyDataReader(Protocol):
    async def get_latest_snapshot(self, inn: str) -> dict[str, Any] | None: ...
    async def get_selection_snapshots(self, snapshot_ids: list[int]) -> list[dict[str, Any]]: ...
    async def list_companies(self, **kwargs) -> list[dict[str, Any]]: ...
    async def find_companies(self, **kwargs) -> dict[str, Any]: ...
    async def get_connection_candidates(self, limit: int = 10001) -> list[dict[str, Any]]: ...
    async def get_snapshots_for_connections(self, inns: list[str]) -> list[dict[str, Any]]: ...
    async def data_source_status(self) -> dict[str, Any]: ...
